### ISSUE TITLE
Incorrect handling of wildcard re-exports (`pub use foo::*`)

### ISSUE THREAD

**Issue by repi** [cargo-public-api/cargo-public-api#101]
If one have one module importing types from another module (in the same crate or another crate) it looks like the output from `cargo-public-api` incorrectly appends the name of the module one was `use`ing - which is not how the type is imported.

Here is an example:

```rust

pub mod v0 {
    pub fn hej() {
        println!("hej!")
    }
}

pub mod v1 {
    // this API is additive to v0, so let's include the contents of v0
    pub use super::v0::*;

    pub fn hej2() {
        hej();
    }
}
```

This gives the `cargo-public-api` output:

```
pub fn api_test::test()
pub fn api_test::v0::hej()
pub fn api_test::v1::hej2()
pub fn api_test::v1::v0::hej()
pub mod api_test
pub mod api_test::v0
pub mod api_test::v1
pub mod api_test::v1::v0
```

But I believe it really should be:

```diff
  pub fn api_test::test()
  pub fn api_test::v0::hej()
  pub fn api_test::v1::hej2()
- pub fn api_test::v1::v0::hej()
+ pub fn api_test::v1::hej()
  pub mod api_test
  pub mod api_test::v0
  pub mod api_test::v1
- pub mod api_test::v1::v0
```

Because there is no `v1::v0` in the usable public API of the crate, we imported all the types from `v0` into the `v1` module as well.

We do this type of imports _a lot_ in one of our crates, and sometimes with 4-5 nested versions which with this became a bit of a recursive mess right now in the public API listings

**Comment by Enselic** [comment]
Thank you so much for reporting! I can confirm this bug. The wildcard seems to confuse cargo-public-api. If we change `pub use super::v0::*;` to `pub use super::v0::hej;` then the output becomes correct:

```
pub fn api_test::v0::hej()
pub fn api_test::v1::hej()
pub fn api_test::v1::hej2()
pub mod api_test
pub mod api_test::v0
pub mod api_test::v1
```

But it should also work with a wildcard.

**Comment by repi** [comment]
thanks for confirming!

**Comment by Enselic** [comment]
Should be fixed by https://github.com/Enselic/cargo-public-api/pull/104. I have added a regression test based on your use case, but if you have any possibility to test the fix more broadly in your ecosystem, that would be great. Thank you so much again for reporting this :)

**Comment by repi** [comment]
sweet, that was fast! will try it out.

update: confirmed fixes it in one of our bigger crates

**Comment by Enselic** [comment]
> that was fast

I would have been even faster if I wouldn't have been away for 1,5 hours eating dinner with my wife and kids :grinning: 

Thanks a lot for checking the fix! I will merge it later this evening, and make a new release in max a few days.
