### ISSUE TITLE
[QUESTION] Could --rustdoc-json-toolchain be part of the public API?

### ISSUE THREAD

**Issue by pedromfedricci** [cargo-public-api/cargo-public-api#111]
My use case is that I'm caching a specific version of cargo-public-api in a CI job so that it won't be recompiled every run. The problem is that eventually nightly will be incompatible with the cached version. So I would like to tell cargo-public-api to use a pinned nightly version instead of the latest one. Looking through the repo, I realized that this flag would do the job, but it is undocumented. Could this feature be stabilized in some way?
Thank you for considering it!

**Comment by Enselic** [comment]
It's a funny coincidence, because 3 hours before you filed this issue, I created a PR to stabilize it, because I recently got the insight that it is useful for the exact use case you are describing 😀

See https://github.com/Enselic/cargo-public-api/pull/109 which I will merge and release in the coming days

**Comment by pedromfedricci** [comment]
Oh wow, I did look into the issues before opening this one, but I guess I forgot to look at the PRs as well (oops).
Using `--toolchain` would be intuitive enough, great!
Should I close this now or wait for the merge?

**Comment by Enselic** [comment]
No worries at all! I closed it via PR because that is much more fun than closing via the close button :)

**Comment by pedromfedricci** [comment]
Awesome and thank you!

**Comment by Enselic** [comment]
Heads-up: Newly released [v0.15.0](https://github.com/Enselic/cargo-public-api/releases/tag/v0.15.0) supports an even more convenient syntax to specify toolchain: `cargo +toolchain public-api`

**Comment by pedromfedricci** [comment]
Checking the active toolchain is great! it's working fine with rust-toolchain files :grinning:.
