### ISSUE TITLE
Proposal: Remove `--output-format markdown` support

### ISSUE THREAD

**Issue by Enselic** [cargo-public-api/cargo-public-api#112]
I would like to remove all code related to Markdown output, including the `--output-format` arg itself. But before I do, I wanted to give others a chance to raise objections.

The thing is, I find myself never ever using `--output-format markdown`. So it makes me wonder if anyone uses it. If not, we should remove the code. Removing the code has the following benefits:
* The test suite becomes faster to run because we can remove the Markdown tests
* It becomes easier to develop new features because no regard has to be taken to markdown output
* Maintenance becomes easier because there will be fewer tests to keep up to date. This is especially true for the "expected output" part of the tests, which changes quite frequently.
* The code base becomes simpler

The downsides are:
* If we ever want to add some other output format, we need to bring back `--output-format` again. I think that will be easy though.

The Markdown output format pre-dates the syntax highlighted/token based output format, which over time has turned out to be superior. So Markdown output is just old legacy cruft at this point. At least from my perspective.

If no objections are raised, I plan to remove the code approximately 1 week from now. If discussions arise then I will postpone or abort.

**Comment by repi** [comment]
didn't know the `--output-format markdown` existed :) but tried it out and at least we don't have a need for it.

Think it could be fine to just remove for now including the argument and if there is a future alternative output format one can just add it back then
