### ISSUE TITLE
warn when toolchain is replaced with nightly

### ISSUE THREAD

**Issue by Emilgardis** [cargo-public-api/cargo-public-api#123]
Some type of warning should probably be emited when the used toolchain, specified explicitly or not, is not used for rustdoc.

This due to lessen the belief that `cargo +stable public-api` actually works, even if it doesn't right now.

**Comment by Enselic** [comment]
I don't think `cargo public-api` should warn, but `cargo +stable public-api` should maybe warn, although it is probably tricky to tell the difference from our context?

However, I think it would be useful to print info about what the toolchain-swapping code does when `--verbose` is passed, including for plain `cargo public-api`.
