### ISSUE TITLE
Public member functions & trait impls are missing for wildcard `use`ed module

### ISSUE THREAD

**Issue by repi** [cargo-public-api/cargo-public-api#163]
If one does a wildcard use of an internal module, such as `use xx::*` this will include public types and functions in that module, but it will miss any member functions or trait implementations of types inside that module if the module is not public.

## Example

Given this code:

```rust
mod a {
    pub mod a1 {
        #[derive(Copy, Clone)]
        pub struct Test {}

        impl Test {
            pub fn test2() {}
        }

        pub fn test1() {}
    }
}

pub use a::*;
```

this generates this output which is missing the `test2` member function and the derived `clone` member function:

```
pub fn api_test::a1::test1()
pub mod api_test
pub mod api_test::a1
pub struct api_test::a1::Test
```

but it should be:

```
pub fn api_test::a1::Test::clone(&self) -> api_test::a1::Test
pub fn api_test::a1::Test::test2()
pub fn api_test::a1::test1()
pub mod api_test
pub mod api_test::a
pub mod api_test::a1
pub mod api_test::a::a1
pub struct api_test::a1::Test
pub struct api_test::a::a1::Test
```

if one change `mod a` to `pub mod a` then the member functions are correctly included both under the `a` module and from the `use a::*` statement.

**Comment by Enselic** [comment]
Thank you for reporting! I reduced the code as much as I could and reported as https://github.com/rust-lang/rust/issues/102583. Maybe there are follow-up problems, but let's take them one at a time.

**Comment by repi** [comment]
thanks!

**Comment by Enselic** [comment]
The upstream bug has been fixed in `nightly-2022-10-30`. Here is the output after `rustup update nightly`:

```
$ cargo public-api
impl RefUnwindSafe for api_test::a1::Test
impl Send for api_test::a1::Test
impl Sync for api_test::a1::Test
impl Unpin for api_test::a1::Test
impl UnwindSafe for api_test::a1::Test
pub fn api_test::a1::Test::clone(&self) -> api_test::a1::Test
pub fn api_test::a1::Test::test2()
pub fn api_test::a1::test1()
pub mod api_test
pub mod api_test::a1
pub struct api_test::a1::Test
```

that looks correct, right? In your expected output, you also had

```
pub mod api_test::a
pub mod api_test::a::a1
pub struct api_test::a::a1::Test
```

but since `mod a` is not `pub`, we should not expect that also in the output.

**Comment by repi** [comment]
ah yes that looks correct! thanks!

do a new release soon with that new nightly?

**Comment by Enselic** [comment]
@repi No need for a new release, just do `rustup update nightly`. After that, `cargo public-api` will use the latest nightly with the latest fixes, including this one!

I don't think I want to bump the minimum required nightly version since the rustdoc JSON format has not changed. In general it is a good idea to always use latest nightly to make sure one gets the latest fixes.

So I'll close this issue now. Thanks for confirming it as fixed!

**Comment by repi** [comment]
ah nice! didn't realize it was just a minimum version, thought it was a pinned one. but we have pinning on our side that I'll try and update and see.

**Comment by repi** [comment]
some of our public API listing snapshots now contain 3000 lines of symbols instead of 1200 lines, so a lot were missing from us in the past. great to have this fixed!
