### ISSUE TITLE
Rename project to `cargo-public-api`

### ISSUE THREAD

**Issue by Enselic** [cargo-public-api/cargo-public-api#17]
I would like to rename this project to `cargo-public-api`.

The main reason is that the term "public items" is not widely understood (because it requires people to know that the rustc term for many language constructs is "item"), whereas the term "public api" *is* widely understood.

So for example, we can simplify our project description from

> List and diff public items (the public API) of Rust library crates.

to

> List and diff the public API of Rust library crates.

Another benefit is that the project will be easier to find by people, who are more likely to search for a tool of our kind using the term "public api" than "public items".

And, `cargo public-api --diff-git-checkouts` makes better semantic sense IMO.

## What about `public_items`?

I do *not* however think we should rename `public_items` to e.g. `public_api`. Mainly because that library is working with "rustc items", and not really with "apis". It makes sense for a tool called `cargo-public-api` to be a user-friendly tool that is implemented with a low-level library called `public_items`.

Besides, the API would become weird if we also renamed `public_items`:
* `public_api::public_items_from_rustdoc_json_str` is annoyingly assymetrical
* `public_api::public_api_from_rustdoc_json_str`does not make much sense

**Comment by Enselic** [comment]
FYI @douweschulte. I think I can go ahead with this without causing you too much trouble? See Enselic/public-api#18 for the diff. Let me know if you want me to wait with this until we have landed your ongoing improvements. If you would like me to wait, that is perfectly fine.

Note that I do not plan on renaming `public_items` (see above for motivation).

**Comment by douweschulte** [comment]
Yes that seems fine, I like this name better. Sidenote I always was interested in the reasoning why `cargo-public-api` used hyphens and `public_items` an underline. Otherwise feel free to merge, I can handle these changes easily in my fork.

**Comment by Enselic** [comment]
When I was casually exploring the idea of writing the `public_items` library (before I had thought about the possibility to add a `cargo` subcommand for it), I casually `cargo publish`ed it with the name `public_items` without thinking about it too much. Soon after I realized that `public-items` would have been a better name, but I learned that `crates.io` does not allow renaming it :( It said something like "you can't change _ to -" IIRC.

So, I wonder... maybe we should take this opportunity to also rename `public_items` to `public-api` after all... But it doesn't quite feel like a good name to me, even when I try to make it feel like a good name. But maybe it is mostly a matter of habit.

I am very curious about what you think about potentially also doing a rename from `public_items` to `public-api`, if you don't mind me asking?

**Comment by douweschulte** [comment]
I think both would work as a name. I do not dislike the name `public-api` as that immediately makes it clear that it handles api stuff while items could essentially mean anything. And your last example in the main body `public_api::public_api_from_rustdoc_json_str` could/should be renamed to `public_api::from_rustdoc_string` which I think removes the semantic issue with using `api` in the name. 

If/when Enselic/public_items#34 is worked on and this gives a more tree like data structure the main root of this could be named `Api` which I think would not be a misnomer for what information it carries. 

Maybe it is the lack of habit for me but I would support a name change to `public-api`, also because it has a hyphen and not an underscore ;-). And it is good to hear that it is impossible to rename `_` to `-` to make sure I always double check my naming before publishing.

**Comment by Enselic** [comment]
You make very good points. After getting used to the idea, I now consider a rename of the lib desirable, and will do it at a later point.

At the very least I want to wait until we have landed your lib changes though, because otherwise the merge conflicts will be messy.

Not sure yet if I will coordinate the rename of this cargo wrapper with the lib to make it all happen at the same time. I need to think some more about that.

In the meantime I have created https://github.com/Enselic/public_items/issues/64 for tracking and further discussion related to the rename of the lib itself.

**Comment by Enselic** [comment]
Ok, I think I'm done with the rename of this project now:

```
% cargo install cargo-public-items
% cargo public-items
This project has been renamed to `cargo-public-api`, see https://github.com/Enselic/cargo-public-api
% cargo install cargo-public-api
% cargo public-api
pub fn cargo_public_api::for_self_testing_purposes_please_ignore()
pub mod cargo_public_api
```

* https://crates.io/crates/cargo-public-items
* https://crates.io/crates/cargo-public-api

We'll do the rename of `public_items` at a later point (tracked in https://github.com/Enselic/public_items/pull/65).

Closing.
