### ISSUE TITLE
Pre-resolve git references to support e.g. `HEAD` as second git reference

### ISSUE THREAD

**Issue by mqudsi** [cargo-public-api/cargo-public-api#180]
Specifying `HEAD` instead of `$(git rev-parse HEAD)` should work but it only works if it's the first argument to `--diff-git-checkouts` because its "value" is lost if a different checkout was specified.

i.e.

```
cargo public-api --diff-git-checkouts 0.4.0 HEAD
```

First checks out 0.4.0 then checks out HEAD, but HEAD is now 0.4.0.

In case HEAD is specified, I believe `cargo-public-api` should first internally call `git rev-parse HEAD` to determine the equivalent commit then use that to checkout later.

**Comment by Emilgardis** [comment]
This is documented as a flaw

https://github.com/Enselic/cargo-public-api/blob/8c808fc8546df3705e295cb4b028fce13483a465/cargo-public-api/src/main.rs#L63-L64

grabbing the sha for the HEAD or whatever specifier is used before execution sounds good

**Comment by Enselic** [comment]
Yeah that sounds like a good idea

**Comment by mqudsi** [comment]
You can actually call `git rev-parse xxx` for each value passed in from the command line (not just `HEAD`) to validate it and turn it into an absolute git ref. This lets you catch invalid input earlier.
