### ISSUE TITLE
Group items even if multiple inherent `impl`s are used

### ISSUE THREAD

**Issue by douweschulte** [cargo-public-api/cargo-public-api#251]
```rust
pub struct pdbtbx::PDB
pub struct field pdbtbx::PDB::identifier: core::option::Option<alloc::string::String>
... (more fields)
impl pdbtbx::PDB
impl pdbtbx::PDB
impl pdbtbx::PDB
impl<'a> pdbtbx::PDB
```

This example is from the crate `pdbtbx` where I have used multiple impl blocks on a single struct to allow fro grouping of functions with some general comments about those groups. That is why it stands out so much. But I would assume these impl blocks (just the main block with all attached functions) to not be shown in the list here. An argument could be made to have the functions grouped below their respective impl blocks, especially when generic bounds are used. But this seems to not be the case here.

**Comment by Enselic** [comment]
Thank you for reporting :pray: 

I can see that in rustdoc HTML, each impl item is presented individually, together with the doc of the impl, if any. So I think we should also show each impl item individually.

So what I think we want is for this code:

```rust
pub struct MultipleInherentImpls;

impl MultipleInherentImpls {
    pub fn impl_one() {}
}

impl MultipleInherentImpls {
    pub fn impl_two() {}
}
```

to be rendered like this:

```txt
pub struct comprehensive_api::impls::MultipleInherentImpls
impl comprehensive_api::impls::MultipleInherentImpls
pub fn comprehensive_api::impls::MultipleInherentImpls::impl_one()
impl comprehensive_api::impls::MultipleInherentImpls
pub fn comprehensive_api::impls::MultipleInherentImpls::impl_two()
```

I looked into solving this. The tricky part is what to use to group items. If we use the impl Id for grouping, it works for listing, but not for diffing, since the ID changes. So I think we might need to do some non-trivial changes to item grouping to solve this.

**Comment by Enselic** [comment]
On a second thought, if we collapse all inherent `impl`s into one `impl` item in the output, we don't need to solve the grouping. If we do it like that, the code above would render as:

```txt
pub struct comprehensive_api::impls::MultipleInherentImpls
impl comprehensive_api::impls::MultipleInherentImpls
pub fn comprehensive_api::impls::MultipleInherentImpls::impl_one()
pub fn comprehensive_api::impls::MultipleInherentImpls::impl_two()
```

The public API is (as far as I know) not affected by if inherent `impl`s are split up or not. So maybe it wouldn't be so bad to do that.  :thinking:

**Comment by Emilgardis** [comment]
Actually, the grouping is bad. 😅

```rust
pub struct Foo<T> {
    bar: T,
}

impl Foo<(u8,)>{
    pub fn new(bar: u8) -> Self {
        Self { bar: bar (bar,) }
    }
}

impl<T> Foo<T>
where
    T: std::fmt::Display,
{
    pub fn display(&self) {
        println!("{}", self.bar)
    }
}
```

gives (with `cargo public-api -s`)

```
pub mod public_api_impl
pub struct public_api_impl::Foo<T>
impl public_api_impl::Foo<(u8)>
impl<T> public_api_impl::Foo<T> where T: core::fmt::Display
pub fn public_api_impl::Foo::display(&self)
pub fn public_api_impl::Foo::new(bar: u8) -> Self
```

Which is simply wrong

**Comment by Emilgardis** [comment]
I think it's fine to group the same impl blocks together

**Comment by douweschulte** [comment]
Grouping them together is fine indeed, there should be some reason why these where grouped under a different impl block to start with. But showing a bare `impl crate::Item` for each group is not that nice I think.

**Comment by Emilgardis** [comment]
I'm struggling with coming up with a good solution for this. Perhaps the only option is to have each impl be a container of other `PublicItem`s?

**Comment by Enselic** [comment]
> I'm struggling with coming up with a good solution for this. Perhaps the only option is to have each impl be a container of other `PublicItem`s?

I explored that a bit when trying to figure out how to solve logical grouping (https://github.com/Enselic/cargo-public-api/pull/198).

The main downside of having a tree of `PublicItem`s is that calculating and presenting diffs of public APIs becomes much more complicated.

But it might very well be the case that having a tree of `IntermediatePublicItem` would make sense, and then just flatten the tree into a list of `PublicItem`s.

**Comment by Enselic** [comment]
> I'm struggling with coming up with a good solution for this. Perhaps the only option is to have each impl be a container of other `PublicItem`s?

Yes `impl`s are already quite special, so maybe it would make sense to treat them specially and not shoe-horn them into being `PublicItem`s.

Actually, I think they need to be `PublicItem`s in the final output. But shoe-horning them into being `IntermediatePublicItem`s as is currently the case might not be the best approach.

**Comment by Emilgardis** [comment]
I'm not actively looking at this, do you think #253 could be merged as is?

**Comment by Enselic** [comment]
I'm still a bit concerned about sorted vs not sorted having different items (https://github.com/Enselic/cargo-public-api/pull/253#discussion_r1056538764)

I have an idea on how to solve it that might work both with and without sorting. I'll try that out. Might take some days before I get around doing it though. If it works I'll send a PR for review. If not we can revisit your PR. 

Sounds ok?

**Comment by Emilgardis** [comment]
sounds good!

**Comment by Enselic** [comment]
I think this fixes it: https://github.com/Enselic/cargo-public-api/pull/270

Might need some tweaks, but I feel like the approach is correct, after having tried to attack the problem from a couple of different angels.

But of course feel free to speak up if either of you don't like this solution.
