### ISSUE TITLE
Probable bug in `Builder::clear_toolchain`

### ISSUE THREAD

**Issue by aatifsyed** [cargo-public-api/cargo-public-api#381]
https://github.com/Enselic/cargo-public-api/blob/8268b7e9b0ebbd0a8a06206781652b846901d895/rustdoc-json/src/builder.rs#L244-L247

Looks wrong from a code read. I think it should be:
```
self.toolchain = None
```

**Comment by Enselic** [comment]
Thank you so much for reporting @aatifsyed 🙏 

In the just-published version `0.8.4` of [rustdoc-json](https://crates.io/crates/rustdoc-json/versions) this is now fixed.
