### ISSUE TITLE
Attributes such as `#[non_exhaustive]` are not considered

### ISSUE THREAD

**Issue by Enselic** [cargo-public-api/cargo-public-api#41]
Adding e.g. `#[non_exhaustive]` to an enum can be a breaking API change, but attributes are currently not considered at all by `public_items`.

**Comment by douweschulte** [comment]
Attributes are saved in `Item::attrs` as a `Vec<String>` so it is possible to implement something like this. Of interest are at least:
* non_exhaustive
* cfg/doc_cfg
* must_use

This will likely have to wait until Enselic/cargo-public-api#38, to include this functionality.

**Comment by Enselic** [comment]
Yeah, inspired by a name change to `public-api`, I have actually been thinking if maybe we should change our public API structure from a list of `PublicItem`s to a tree of `PublicItem`s. I think that will allow us to solve Enselic/cargo-public-api#38 quite easily. And with a tree structure it would perhaps be more natural to annotate items in the tree with these kinds of attributes. These are just loose thoughts at the moment, but I think I might be on to something. I saw your updated PR btw, but will need some more time to take a look at it. From what I saw so far it looked ready for a deeper look now :)

**Comment by douweschulte** [comment]
I do wholeheartedly agree with the tree data structure. After the PR (which is indeed ready for a full review, I will still be cleaning it but no major work) I will be happy to discuss it more.

**Comment by Enselic** [comment]
`cfg` we should get for free since rustdoc should not generate items for items that have been configured to not be included in the build.

`doc_cfg` is not stable yet (tracking issue: https://github.com/rust-lang/rust/issues/43781), so formally we are not required to handle that.

I agree we need to support `non_exhaustive` and `must_use`. Let me know if you can think of any more relevant attributes. I can't right now off the top of my head.

**Comment by douweschulte** [comment]
I think these are the most important. And once these are in place it should be substantially easier to add any others that come around.
Reference for all rust attributes: https://doc.rust-lang.org/reference/attributes.html#built-in-attributes-index.

**Comment by Enselic** [comment]
After looking into it even more I don't even think we should do anything with `#[must_use]`, because our gold standard `cargo doc` HTML output does not mention it. It only affect whether or not a lint/warning will be printed if e.g. the return value of a function is not used, but strictly speaking it does not change the API.

I think this is a comprehensive list of all attributes we need to worry about:

```
const ALLOWED_ATTRIBUTES: &[Symbol] =
    &[sym::export_name, sym::link_section, sym::no_mangle, sym::repr, sym::non_exhaustive];
```
https://github.com/rust-lang/rust/blob/68d0b29098ed75f50dabc7d07b96c70caab5c182/src/librustdoc/html/render/mod.rs#L941-L942
