### ISSUE TITLE
Make error message more helpful when `rustup` is not in `PATH`

### ISSUE THREAD

**Issue by matthiasbeyer** [cargo-public-api/cargo-public-api#512]
I just cloned a fresh repository and executed `cargo public-api` on it.

Its output was `Error: No such file or directory (os error 2)` which is not very descriptive of what went wrong.

Please consider this a bugreport.

**Comment by Emilgardis** [comment]
can you run `cargo metadata` in the repository? Would you be able to link the specific repository?

**Comment by matthiasbeyer** [comment]
The repository is env_logger: https://github.com/rust-cli/env_logger - from `main` branch. Yes I can run `cargo-metadata`, but I am not sure - do you want me to paste that big JSON blob here?

**Comment by Emilgardis** [comment]
Are you certain there's no more error output? Can you show me

```sh
$ ls
$ cargo public-api
```

**Comment by matthiasbeyer** [comment]
![image](https://github.com/Enselic/cargo-public-api/assets/427866/29442258-590a-48cc-91e3-5e8736ad8d94)

**Comment by Emilgardis** [comment]
can you do `cargo --list -v` and confirm that public-api is in there, and then try to directly run the binary it's pointing to

**Comment by Emilgardis** [comment]
oh, also `cargo +nightly -V`

**Comment by matthiasbeyer** [comment]
Yep it is there and:

```
$ $(which cargo-public-api)
Error: No such file or directory (os error 2)
```

**Comment by Emilgardis** [comment]
The error message suggests that it's actually run, so not a loader problem afaik.

It's probably the cache or something else, we're missing some context spans for anyhow that we could add to improve this.

what's the output of above? I suggested it to just ensure that the nightly toolchain is installed

**Comment by matthiasbeyer** [comment]
Ah, this needs nightly?

Well... maybe there should be a check that nightly is actually there! :laughing:

**Comment by Emilgardis** [comment]
There is a check, do you have rustup installed?

**Comment by matthiasbeyer** [comment]
No, there is no rustup on my system!

**Comment by Emilgardis** [comment]
aha! well there we go, that's the problem :D

We should make the error message better.

To use `rustdoc-json` which we need, a nightly toolchain is needed. The easiest way to handle that is by using rustup

**Comment by Emilgardis** [comment]
pretty sure this is where the error is bubbled up from

https://github.com/Enselic/cargo-public-api/blob/3e3448376082b389eeb2c3943e24439dba0b124c/rustdoc-json/src/builder.rs#L20

an easy fix would be to add a `.with_context(|| format!("couldn't run command {}", cmd.get_program()))`
we should make

https://github.com/Enselic/cargo-public-api/blob/3e3448376082b389eeb2c3943e24439dba0b124c/rustdoc-json/src/lib.rs#L49-L51

not transparent, and also implement a specific check for rustup (and probably only if the above command fails) to make the error message better. We already check for rustup earlier in the stack, so maybe we can utilize those calls

**Comment by matthiasbeyer** [comment]
Am working on this.

**Comment by Enselic** [comment]
Thanks for reporting!

To whom it may concern: Note that the above PR was closed, so no one is working on fixing this right now. Would be nice to get fixed even though it is a bit of an edge-case to not have rustup installed.
