### ISSUE TITLE
New `rustdoc-json` minor release?

### ISSUE THREAD

**Issue by fornwall** [cargo-public-api/cargo-public-api#530]
Would it be possible with a minor release of `rustdoc-json`? Would be nice having https://github.com/Enselic/cargo-public-api/pull/525 released, as it would cleanup some duplicated dependencies for many consumers.

**Comment by Enselic** [comment]
Sure, no problem. [Done](https://crates.io/crates/rustdoc-json/0.8.9) 🚀

**Comment by fornwall** [comment]
Thanks a lot!
