### ISSUE TITLE
Bump minimum supported nightly version

### ISSUE THREAD

**Issue by CosmicHorrorDev** [cargo-public-api/cargo-public-api#571]
Per https://github.com/serde-rs/serde/issues/2734#issuecomment-2089631549 it may be a good idea to bump `public_api::MINIMUM_NIGHTLY_RUST_VERSION` to a higher nightly to avoid hitting a common compilation issue with `serde` that can't be reverted at this point without breaking backwards compatibility

**Comment by Emilgardis** [comment]
`public_api::MINIMUM_NIGHTLY_RUST_VERSION` is not the traditional MSRV for the crate, its the minimum version of rustdoc json that is supported. Are you experiencing any problems due to us specifying the minimum supported version?

**Comment by Enselic** [comment]
public_api::MINIMUM_NIGHTLY_RUST_VERSION is concerned with the format of the rustdoc JSON produced by the given nightly. If another crate (syntect) has additional requirements on minimum nightly version for other reasons (serde in this case) that other crate is free to use a higher version of nightly. public_api::MINIMUM_NIGHTLY_RUST_VERSION  is just a string like "nightly-YYYY-MM-DD" so you can pass any nightly in syntect as the toolchain to use. I don't see anything actionable here from our side.

**Comment by CosmicHorrorDev** [comment]
The issue to me is that `serde` is an incredibly common dep that will consistently fail to compile with the specific version that's called out by `public_api` which seems to be more-or-less the standard way of pinning a nightly version that's supposed to work (or at least the current examples all wind up using it that way)

That seemed problematic enough to me to justify raising the minimum version this time as an exception, but if not then feel free to just close this

**Comment by Enselic** [comment]
I guess we could make things clearer in the documentation.

In this particular case, would any additional or changed documentation have helped? If not, then I think we can close this issue. I can see how you think, but I respectfully disagree :)

If there _is_ some way of documenting this that would have helped you, it would be fantastic if you could share it, so we can improve the docs.
