### ISSUE TITLE
Features in combination with diff

### ISSUE THREAD

**Issue by jwiesler** [cargo-public-api/cargo-public-api#573]
I'm trying to use public-api with features in the diff mode. However, `--features` eats all following strings, e.g.:
```
cargo public-api --features runtime-tokio-hyper,async diff HEAD..master 
```
This runs the normal public-api with features `runtime-tokio-hyper`, `async` `diff` `HEAD..master`.

Is there any way to provide these features? I tried quoting and with or without `,` between.

**Comment by Emilgardis** [comment]
the problem is 

https://github.com/Enselic/cargo-public-api/blob/5c8a62be427ee28eb6a23c86889f33d1fda7ca7c/cargo-public-api/src/main.rs#L60

`1..`, we should probably not set that, since that's not how it's done in cargo, you need to use multiple `--features` or separate with `,`. It requires that precisely to avoid this issue

**Comment by jwiesler** [comment]
Yep, that makes sense.

**Comment by jwiesler** [comment]
Should I open a mr or do you want to fix that?

**Comment by Emilgardis** [comment]
Yes, feel free to submit a fix. Also, there is a way around this. `--features` is global so you can specify it after diff and its argument

```
cargo public-api diff HEAD..master --features runtime-tokio-hyper async
```

**Comment by jwiesler** [comment]
For me this outputted expected 1 or 2 args got 3

**Comment by Emilgardis** [comment]
hmm, might be something else strange happening with that specific case

**Comment by Enselic** [comment]
Are you testing with git main @jwiesler ? We have not published that fix yet to crates.io

**Comment by jwiesler** [comment]
Nope, I used the crates.io version. I see the commit is from 2 weeks ago, is there anything blocking you from publishing?

**Comment by Enselic** [comment]
Well, I'd really like to see this bug fixed before I publish a new version. Did you encounter any obstacles when trying to fix?

**Comment by jwiesler** [comment]
No, I just didn't find any time yet, and I probably won't this week.

**Comment by jwiesler** [comment]
I can confirm that it works on master as expected.

I checked:
- `"feature-a feature-b"`
- `"feature-a,feature-b"`
- `feature-a,feature-b`

Would be cool if you'd release a new version on crates.io if you didn't already :)

**Comment by Enselic** [comment]
According to my testing it's not working quite right.

**Comment by Enselic** [comment]
With https://github.com/Enselic/cargo-public-api/pull/580 it works the same as with cargo according to my testing (and the new regression tests).

This works with cargo:

```
cargo build --features "feature_a feature_b"
```

but not this

```
cargo build --features feature_a feature_b
```

and with my PR it seems to work the same with cargo-public-api.
