### ISSUE TITLE
Failure with `nightly-2024-09-10` and later due to renamed rustdoc JSON elements

### ISSUE THREAD

**Issue by Billy99** [cargo-public-api/cargo-public-api#616]
With recent rust nightly build (nightly-2024-09-10), public-api commands are failing on upstream projects (https://github.com/aya-rs/aya and https://github.com/bpfman/bpfman are hitting issue). Looks like rust-lang, via [PR130133](https://github.com/rust-lang/rust/pull/130133) pulled in [PR128667](https://github.com/rust-lang/rust/pull/128667). I believe https://github.com/aDotInTheVoid/rustdoc-types needs to be updated to take into account these changes and a new release created (see [rustdoc-types:Issue32](https://github.com/aDotInTheVoid/rustdoc-types/issues/32)) and then this repo needs to pull in that rustdoc-types release.

**Comment by Enselic** [comment]
Our [nightly job](https://github.com/cargo-public-api/cargo-public-api/actions/workflows/Nightly.yml) has indeed been failing for (now) three days, and I think your assessment on how to fix it is right.

**Comment by Billy99** [comment]
https://github.com/aDotInTheVoid/rustdoc-types/issues/32 has been addressed by [rustdoc-types:v0.30.0](https://github.com/aDotInTheVoid/rustdoc-types/releases/tag/v0.30.0).

**Comment by cyypherus** [comment]
Here's a scrappy CI workaround for the time-being :)

```
      - name: Install nightly & cargo-public-api
        run: |
          set -euxo pipefail

          rustup install nightly-2024-07-05 --profile minimal
          mv ~/.rustup/toolchains/nightly-2024-07-05-x86_64-unknown-linux-gnu ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
```

**Comment by Enselic** [comment]
Let's keep this open until a release is out.

**Comment by Enselic** [comment]
> Here's a scrappy CI workaround for the time-being :)
> 
> ```
>       - name: Install nightly & cargo-public-api
>         run: |
>           set -euxo pipefail
> 
>           rustup install nightly-2024-07-05 --profile minimal
>           mv ~/.rustup/toolchains/nightly-2024-07-05-x86_64-unknown-linux-gnu ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
> ```

No need for hacks. You can simply do `cargo +nightly-2024-07-05 public-api` :)

**Comment by cyypherus** [comment]
Ah good point, my case involved the [cargo install](https://github.com/marketplace/actions/cargo-install) action so i didn't have that option.

**Comment by tamird** [comment]
What has to happen to get a new release out?

**Comment by Enselic** [comment]
See the discussion here: https://github.com/cargo-public-api/cargo-public-api/pull/625#issuecomment-2358261304

**Comment by tamird** [comment]
Acknowledged, but I don't see anything relevant there. The PR has been merged, what remains to be done?

**Comment by Enselic** [comment]
Go through https://github.com/cargo-public-api/cargo-public-api/blob/main/docs/RELEASE.md in detail and for example update the compatibility matrix

**Comment by tamird** [comment]
AFAICT the only thing left to do _is_ to update the compatibility matrix:
```diff
diff --git a/README.md b/README.md
index 40f3220..226d412 100644
--- a/README.md
+++ b/README.md
@@ -142,6 +142,7 @@ cargo public-api -sss
 
 | Version          | Understands the rustdoc JSON output of  |
 | ---------------- | --------------------------------------- |
+| 0.38.x           | nightly-2024-09-10 —                    |
 | 0.37.x           | nightly-2024-07-05 — nightly-2024-09-09 |
 | 0.35.x — 0.36.x  | nightly-2024-06-07 — nightly-2024-07-04 |
 | 0.32.x — 0.34.x  | nightly-2023-08-25 — nightly-2024-06-06 |

```

Everything else requires maintainer access :(

**Comment by Billy99** [comment]
I'll push a PR with the compatibility matrix now. I had it in an earlier PR and was asked to remove it. I guess I did it too soon in the process.

**Comment by Enselic** [comment]
(My comment on the PR was only for the particular line I commented on, and then I didn't see that you removed it )

**Comment by Enselic** [comment]
I finally got time to sit down and to the final step of the release. It's [done](https://github.com/cargo-public-api/cargo-public-api/releases/tag/v0.38.0). Thanks @Billy99 for help with preparing.

If this becomes a reoccurring problem, we can look into adding more people to our github org to help with making releases.
