### ISSUE TITLE
Update needed since nightly 2024-10-13

### ISSUE THREAD

**Issue by tamird** [cargo-public-api/cargo-public-api#631]
Upstream: https://github.com/rust-lang/rust/pull/130078

See: https://github.com/aya-rs/aya/actions/runs/11311392733/job/31457575922

**Comment by Enselic** [comment]
Our [nightly job](https://github.com/cargo-public-api/cargo-public-api/actions/workflows/Nightly.yml) indeed started failing with nightly-2024-10-13

Fixed by https://github.com/cargo-public-api/cargo-public-api/pull/633
