### ISSUE TITLE
Add `id` and `parent_id` functions, and one other small request

### ISSUE THREAD

**Issue by smoelius** [cargo-public-api/cargo-public-api#655]
As alluded to in #627, I am using a fork of `public-api` to generate wrappers for standard library functions and types.

To avoid using the fork, I was wondering if you would consider the following changes:
- Add an `id` function to return the `rustdoc_types::Id` from which a `PublicItem` was constructed
- Add a `parent_id` function to return the `rustdoc_types::Id` of the `PublicItem`'s parent, if one exists
- Eliminate the `name != "_"` condition in the following code so that a variable name is always emitted: https://github.com/cargo-public-api/cargo-public-api/blob/0fb7f150a88da4eba85e84f1ad12b98cc7258487/public-api/src/render.rs#L468-L470

If you prefer, I could submit a PR to show you the changes I am imagining.

Thanks regardless of what you decide.

**Comment by Enselic** [comment]
I think your proposal is reasonable enough to make it worthwhile to create a draft PR so we can get a feeling for the details before making a decision.

If it looks ok then and if you agree to help maintain this API surface I think it should be fine. (But other maintainers might have stronger objections.)

**Comment by smoelius** [comment]
> I think your proposal is reasonable enough to make it worthwhile to create a draft PR so we can get a feeling for the details before making a decision.

The draft PR is #656.

**Comment by smoelius** [comment]
#656 was merged.

**Comment by smoelius** [comment]
Thanks again!
