### ISSUE TITLE
Support 2024 edition

### ISSUE THREAD

**Issue by SUPERCILEX** [cargo-public-api/cargo-public-api#665]
```
    CargoManifestError(Parse(Error {
        inner: Error {
            inner: TomlError {
                message: "data did not match any variant of untagged enum MaybeInherited",
                raw: Some(
                    "[package]\nname = \"supercilex-tests\"\nversion = \"0.4.11\"\nauthors = [\"Alex Saveau <saveau.alexandre@gmail.com>\"]\nedition = \"2024\"\ndescription = \"Test utilities I use.\"\nrepository = \"https://github.com/SUPERCILEX/supercilex-tests\"\nkeywords = [\"test-utils\"]\ncategories = [\"development-tools::testing\"]\nlicense = \"Apache-2.0\"\n\n[dependencies]\nclap_builder = { version = \"4.5.21\", default-features = false, features = [\"std\"], optional = true }\nexpect-test = { version = \"1.5.0\", optional = true }\npublic-api = { version = \"0.42.0\", optional = true }\nrustdoc-json = { version = \"0.9.3\", optional = true }\n\n[features]\ndefault = [\"api\", \"clap\"]\napi = [\"dep:expect-test\", \"dep:public-api\", \"dep:rustdoc-json\"]\nclap = [\"dep:clap_builder\", \"dep:expect-test\"]\n",
                ),
                keys: ["package", "edition"],
                span: Some(120..126),
            },
        },
    }))
```

**Comment by Enselic** [comment]
Can you give some more context please? First of all, how do you reproduce this? In what way is cargo-public-api involved?

**Comment by SUPERCILEX** [comment]
My bad, I assumed any 2024 edition was broken. Clone https://github.com/SUPERCILEX/supercilex-tests and run `UPDATE_EXPECT=1 cargo t --workspace` to get the error. Notice that flipping this to 2021 makes the error go away: https://github.com/SUPERCILEX/supercilex-tests/blob/9cab8e9091d44371bdd9eeec78e7a0590cb26230/Cargo.toml#L5

**Comment by SUPERCILEX** [comment]
The crash originates in the rustdoc_json builder: https://github.com/SUPERCILEX/supercilex-tests/blob/9cab8e9091d44371bdd9eeec78e7a0590cb26230/src/lib.rs#L84

**Comment by SUPERCILEX** [comment]
@Enselic turns out this is fixed by cargo-manifest 0.17! See https://github.com/LukeMathWalker/cargo-manifest/commit/a46ae59b89c78f2cac779ed5068b4294a682b574. Looks like all that's needed is a new release of rustdoc_json.

**Comment by Enselic** [comment]
Great! I'm off for some time, but it would be great if you could prepare a release-PR. All you need to know should be in https://github.com/cargo-public-api/cargo-public-api/blob/main/docs/RELEASE.md. If not that's a bug in the docs.

**Comment by Enselic** [comment]
Fix published: https://crates.io/crates/rustdoc-json/0.9.4

**Comment by SUPERCILEX** [comment]
Sweet, thanks for the present lol. Happy holidays! :)
