### ISSUE TITLE
QUESTION: Why does this crate need web access?

### ISSUE THREAD

**Issue by stevenroose** [cargo-public-api/cargo-public-api#666]
Was building this crate and noticed it needs openssl as a dependency.

Found out that it's using the `curl` crate. 

Why exactly does a crate that parses Rust code for a public API need a web client?

**Comment by Enselic** [comment]
To download published crates for api diffing as described in the readme.

Only needed for cargo-public-api. Not for the public-api crate which is the actual parser crate and what you use for CI testing, as also described in the readme.

**Comment by Enselic** [comment]
Why ask that though? If this project was malicious I would still reply just like I did.

What you need to do is to audit the code for backdoors. E.g. by git gripping for how curl is used.

My favorite command for auditing code in repos is:

`git ls-files | xargs bat`

But this is assuming you build from git. If you build from crates.io you of course need to audit the code you actually download.
