### ISSUE TITLE
Allow using `-p` to select package in workspace

### ISSUE THREAD

**Issue by Enselic** [cargo-public-api/cargo-public-api#82]
If you stand in the root of this git repo, you can run this command to build the HTML docs of say the `rustdoc-json` crate:

```bash
cargo doc -p rustdoc-json
```

It would be convenient to be able to use the same flag for `cargo public-api`, like this:
```bash
cargo public-api -p rustdoc-json
```

because currently you have to use the much longer:

```bash
cargo public-api  --manifest-path rustdoc-json/Cargo.toml
```

which means you can barely re-use the `cargo doc` command from your shell history. It is worth noting that `cargo doc` also support the longer form that we currently use:

```
cargo doc --manifest-path rustdoc-json/Cargo.toml
```

Type `cargo help doc` and read the **Package Selection** section for more info on how package selection works with `cargo doc`.

**Comment by matthiasbeyer** [comment]
This would (at best) need this functionality in the `rustdoc_json` crate, right?

**Comment by Enselic** [comment]
Good question!

Ideally the logic to resolve package names would reside in a separate crate I think. I looked a bit at the cargo source code but it didn't seem to use a separate crate for it unfortunately.

I don't think the rustdoc_json crate should have code to resolve cargo packages though, as I consider that out-of-scope. There is not much code to re-use in there anyway, I think. But I am open to change my mind if the code turns out to be great.

Unless we find a crate for it, my first attempt would be to add it to the cargo-public-api crate itself. That's where the current and related --manifest-path logic resides.

**Comment by Enselic** [comment]
Maybe we can use https://docs.rs/cargo_toml/0.11.5/cargo_toml/struct.Workspace.html somehow? We already depend on `cargo_toml` so if that works somehow it would be very nice.

**Comment by Enselic** [comment]
I had forgotten that `rustdoc_json` already had a direct dependency on `cargo_toml`. Now I think it might be quite sensible to add a `package: Option<String>` corresponding to `-p` to `rustdoc_json::BuildOptions`.
