### ISSUE TITLE
Inspecting the standard library

### ISSUE THREAD

**Issue by Michael-F-Bryan** [cargo-public-api/cargo-public-api#91]
I would like a way to automatically find all the types in `std`, but naively pointing `cargo public-api` at `std` fails because it can't find `core` and other dependencies. 

```console
$ cargo public-api --manifest-path $(rustc --print sysroot)/lib/rustlib/src/rust/library/std/Cargo.toml
Error: Failed to build rustdoc JSON. Stderr:     Checking compiler_builtins v0.1.78
    Checking libc v0.2.127
   Compiling unwind v0.0.0 (/home/michael/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/unwind)
error[E0433]: failed to resolve: could not find `prelude` in `core`

error[E0432]: unresolved import `core::ops`
 --> /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.78/src/float/mod.rs:1:5
  |
1 | use core::ops;
  |     ^^^^^^^^^ no `ops` in the root

error[E0432]: unresolved import `core::intrinsics`
  --> /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.78/src/mem/mod.rs:11:11
   |
11 | use core::intrinsics::{atomic_load_unordered, atomic_store_unordered, exact_div};
   |           ^^^^^^^^^^ could not find `intrinsics` in `core`

...
```

Presumably `rustc` does something funky with the sysroot that `cargo public-api` doesn't).

Do you have any suggestions for how I might be able to achieve this?

**Comment by Enselic** [comment]
Thanks for reporting! I'm not at a computer until Friday, so I can't check, but I assume using plain `rustdoc` can't build rustdoc JSON for std either? That makes this an upstream problem that should be reported upstream, as a first step.

Once that work it might very well be the case that we need to tweak how we build rustdoc JSON for this use case.

**Comment by Enselic** [comment]
Building regular rustdoc HTML for std requires a special dance, see https://github.com/rust-lang/rust/blob/75b7e52e92c3b00fc891b47f5b2efdff0a2be55a/src/bootstrap/doc.rs#L427-L523

Not sure how to do it without x.py in the rust-lang/rust repo even for regular rustdoc HTML, let alone for rustdoc JSON

I am not able to prioritise further investigation into this at the moment I'm afraid

But it seems like a reasonable long-term enhancement request on this tool nevertheless

**Comment by Enselic** [comment]
Here is an upstream issue that is about shipping pre-built rustdoc JSON for e.g. `std`. Not sure if it helps you, but could be good to know about: https://github.com/rust-lang/rust/issues/101383

**Comment by Enselic** [comment]
Pre-built rustdoc JSON for e.g. std and core is now available, so I added a new flag `--rustdoc-json` to allow listing the public API of e.g. core and std. See #177 for more info.

After thinking some more about this, I don't think it would be a good idea for this project to duplicate the Rust bootstrapping scripts to allow building e.g. std, so I propose that we consider this ticket closed by that PR.

But as always, I am open to discuss this if there is any disagreement.
